### ISSUE TITLE
Request help debug: I occur a bug when reproduce the winequality dataset

### ISSUE THREAD

**Issue by luozhengdong** [yandex-research/tabular-dl-tabr#14]
what the code I change as follow:
```
cp -r exp/tabr/why/regression-num-medium-2-wine_quality/ exp/tabr/why/regression-num-medium-3-wine_quality/
cp -r data/regression-num-medium-2-wine_quality/ data/regression-num-medium-3-wine_quality/
cp exp/tabr/why/regression-num-medium-3-wine_quality/0-tuning.toml exp/tabr/why/regression-num-medium-3-wine_quality/1-tuning.toml
```
In 'data/regression-num-medium-3-wine_quality/info.json', change 'regression-num-medium-2-wine_quality' to 'regression-num-medium-3-wine_quality'
In 'exp/tabr/why/regression-num-medium-3-wine_quality/1-tuning.toml', change ''data/regression-num-medium-2-wine_quality'' to ''data/regression-num-medium-3-wine_quality''

```
python bin/tune.py exp/tabr/why/regression-num-medium-2-wine_quality/1-tuning.toml
```
```
python bin/tune.py exp/tabr/why/regression-num-medium-3-wine_quality/1-tuning.toml
```
Then 'python bin/tune.py exp/tabr/why/regression-num-medium-2-wine_quality/1-tuning.toml' is ok, but 'python bin/tune.py exp/tabr/why/regression-num-medium-3-wine_quality/1-tuning.toml', 
![image](https://github.com/yandex-research/tabular-dl-tabr/assets/44635958/acdd8679-a1d9-43ed-8815-3174cf855495)
```
[W 2023-11-17 18:09:18,793] Trial 0 failed with value None.
  0%|                                                                                       | 0/100 [00:48<?, ?it/s]
Traceback (most recent call last):
  File "~/bin/tune.py", line 216, in <module>
    lib.run_Function_cli(main)
  File "~/tabR_lzd/lib/util.py", line 276, in run_Function_cli
    function(
  File "~/tabR_lzd/bin/tune.py", line 202, in main
    study.optimize(
  File "~/anaconda3/envs/torch/lib/python3.9/site-packages/optuna/study/study.py", line 442, in optimize
    _optimize(
  File "~/anaconda3/envs/torch/lib/python3.9/site-packages/optuna/study/_optimize.py", line 66, in _optimize
    _optimize_sequential(
  File "~/anaconda3/envs/torch/lib/python3.9/site-packages/optuna/study/_optimize.py", line 163, in _optimize_sequential
    frozen_trial = _run_trial(study, func, catch)
  File "~/anaconda3/envs/torch/lib/python3.9/site-packages/optuna/study/_optimize.py", line 251, in _run_trial
    raise func_err
  File "~/anaconda3/envs/torch/lib/python3.9/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "~/tabR_lzd/bin/tune.py", line 161, in objective
    report = function(raw_config, Path(tmp) / 'output')  #the objective function, in turn, calls the function = "bin.tabr.main"
  File "~/tabR_lzd/bin/tabr.py", line 595, in main
    metrics, predictions, eval_batch_size = evaluate(
  File "~/anaconda3/envs/torch/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "~/tabR_lzd/bin/tabr.py", line 549, in evaluate
    dataset.calculate_metrics(predictions, report['prediction_type'])
  File "~/tabR_lzd/lib/data.py", line 235, in calculate_metrics
    metrics = {
  File "~/tabR_lzd/lib/data.py", line 236, in <dictcomp>
    part: calculate_metrics_(
  File "~/tabR_lzd/lib/metrics.py", line 58, in calculate_metrics
    'rmse': sklearn.metrics.mean_squared_error(y_true, y_pred) ** 0.5 * y_std,
  File "~/anaconda3/envs/torch/lib/python3.9/site-packages/sklearn/utils/_param_validation.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "~/anaconda3/envs/torch/lib/python3.9/site-packages/sklearn/metrics/_regression.py", line 474, in mean_squared_error
    y_type, y_true, y_pred, multioutput = _check_reg_targets(
  File "~/anaconda3/envs/torch/lib/python3.9/site-packages/sklearn/metrics/_regression.py", line 101, in _check_reg_targets
    y_pred = check_array(y_pred, ensure_2d=False, dtype=dtype)
  File "~/anaconda3/envs/torch/lib/python3.9/site-packages/sklearn/utils/validation.py", line 951, in check_array
    raise ValueError(
ValueError: Found array with dim 3. None expected <= 2.
```
How to debug?
Thanks!

**Comment by Yura52** [comment]
> Then 'python bin/tune.py exp/tabr/why/regression-num-medium-2-wine_quality/1-tuning.toml' is ok

This command cannot be ok, because this file does not exist in the repository. 

> but 'python bin/tune.py exp/tabr/why/regression-num-medium-3-wine_quality/1-tuning.toml',

This command works for me (after all previous commands) without any issues.

**Comment by Yura52** [comment]
I highly recommend reading errors produced by the Python interpreter, they are often very helpful.

For example, the error that you pasted says:

```
ValueError: Found array with dim 3. None expected <= 2.
```

It means that, at some point, your code produced a PyTorch tensor (or a NumPy array) of an unexpected shape. Similarly, in the middle of the traceback, it says:

```
'rmse': sklearn.metrics.mean_squared_error(y_true, y_pred) ** 0.5 * y_std,
```

So it is the place from where you can start debugging.

**Comment by Yura52** [comment]
Feel free to reopen the issue if needed!
